# Use the README file as a reference to customize settings.

Tag:
  fields:
    default: name, expenses
    form: name
  filters: created_at
  search: name
  relationships: expenses
  application: Application
  options:
    default_action_on_item: show
